_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: ''
homepageEnabled: true
homepageGroup: Tools
homepageIcon: actual
homepageName: Actual Budget
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: ynab.crt.house
ingName: actualbudget
ingPathType: Prefix
ingWebSockets: false
ingress: true
labels: 'app: actualbudget'
name: actualbudget
namespace: actualbudget
pvc: true
pvcAccessMode: ReadWriteMany
pvcName: actualbudget
pvcSize: 1Gi
pvcStorageClass: nfs-critical
reloader: false
resources:
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- services.yaml
service: true
serviceAccount: true
svcAccountName: actualbudget
svcName: actualbudget
svcPortName: http
svcPortNum: 5006
svcProtocol: TCP
svcSelector: 'app: actualbudget'
svcTargetPort: http
svcType: ClusterIP
upstreamURL: https://actualbudget.org/
url: https://github.com/charlesthomas/homelab-actualbudget
