---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-actualbudget
commonLabels:
  app: actualbudget

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml

images:
  - name: actual-server
    newName: ghcr.io/actualbudget/actual-server
    newTag: 25.7.0

patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: actualbudget
      namespace: actualbudget
      annotations:
        gethomepage.dev/href: https://ynab.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: "YNAB Replacer"
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: actual-budget
        gethomepage.dev/name: Actual Budget
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
