---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: actualbudget
  namespace: longhorn # must be longhorn
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
  - actualbudget
  labels:
    app: actualbudget
  name: actualbudget
  retain: 7
  task: 

