---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      containers:
        - name: actualbudget
          image: "ghcr.io/actualbudget/actual-server:24.10.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources: {}
          volumeMounts:
            - mountPath: /old
              name: old
            - mountPath: /data
              name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: actualbudget
      - name: old
        nfs:
          path: /volume1/critical/k3s/actualbudget-actualbudget-pvc-b06b4034-4586-4cb7-b321-c12f0b577960
          server: 192.168.1.21
