---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
